import type { InventoryItem } from "../types/inventory.types";

export const FAKE_INVENTORY: InventoryItem[] = [
  {
    id: 1,
    name: "Ballpen Black",
    category: "Writing",
    stock: 120,
    lastRestocked: "May 1, 2026",
  },
  {
    id: 2,
    name: "Ballpen Blue",
    category: "Writing",
    stock: 98,
    lastRestocked: "May 1, 2026",
  },
  {
    id: 3,
    name: "Ballpen Red",
    category: "Writing",
    stock: 2,
    lastRestocked: "Apr 20, 2026",
  },
  {
    id: 4,
    name: "Pencil #2",
    category: "Writing",
    stock: 200,
    lastRestocked: "May 5, 2026",
  },
  {
    id: 5,
    name: "Notebook A4",
    category: "Notebooks",
    stock: 55,
    lastRestocked: "May 3, 2026",
  },
  {
    id: 6,
    name: "Notebook A5",
    category: "Notebooks",
    stock: 40,
    lastRestocked: "May 3, 2026",
  },
  {
    id: 7,
    name: "Folder Long",
    category: "Folders",
    stock: 80,
    lastRestocked: "Apr 28, 2026",
  },
  {
    id: 8,
    name: "Folder Short",
    category: "Folders",
    stock: 60,
    lastRestocked: "Apr 28, 2026",
  },
  {
    id: 9,
    name: "Eraser Big",
    category: "Others",
    stock: 3,
    lastRestocked: "Apr 15, 2026",
  },
  {
    id: 10,
    name: "Ruler 30cm",
    category: "Others",
    stock: 45,
    lastRestocked: "Apr 30, 2026",
  },
  {
    id: 11,
    name: "Scotch Tape",
    category: "Others",
    stock: 4,
    lastRestocked: "Apr 25, 2026",
  },
  {
    id: 12,
    name: "Crayon Set",
    category: "Art",
    stock: 0,
    lastRestocked: "Apr 10, 2026",
  },
  {
    id: 13,
    name: "Watercolor",
    category: "Art",
    stock: 20,
    lastRestocked: "May 2, 2026",
  },
  {
    id: 14,
    name: "Bond Paper",
    category: "Paper",
    stock: 500,
    lastRestocked: "May 6, 2026",
  },
  {
    id: 15,
    name: "Pad Paper",
    category: "Paper",
    stock: 80,
    lastRestocked: "May 4, 2026",
  },
  {
    id: 16,
    name: "Scissor",
    category: "Others",
    stock: 30,
    lastRestocked: "Apr 22, 2026",
  },
];
